[package]
name = "anthill-window-lib"
version = "0.1.0"
authors = ["Vidrochka <Evgenuy1605@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
