[package]
name = "anthill-window-lib"
version = "0.1.0"
authors = ["Vidrochka <Evgenuy1605@yandex.ru>"]
edition = "2018"
build = "build.rs"

[dependencies]
anthill-di = "*"
derive_builder = "*"
gl = "*"

[dependencies.sdl2]
version = "*"
default-features = false